version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    env_file: .env
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - npm-nw

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT:-5061}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - npm-nw
    restart: unless-stopped

volumes:
  data:


networks:
  npm-nw:
    external: true
