version: "3.3"

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - npm-nw

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - npm-nw
    restart: unless-stopped

  pgagent:
    image: chiavegatto/postgres-pgagent:latest
    entrypoint: /bin/sh -c "/tmp/wait-for-it.sh postgres:5432 --timeout=30 && PGPASSWORD='123456' psql -U postgres -h postgres -p 5432 -d neygift -c 'CREATE EXTENSIO$
    environment:
      - TIMEZONE=Asia/Tehran

volumes:
  data:


networks:
  npm-nw:
    external: true
